version: "3.3"

services:
  database:
    container_name: postgres-arm32v7
    build: ./db
    env_file:
      - ./db/.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pg_data:/pg-data
    ports:
      - "5432:5432"
    restart: always
    user: 999:1001
  telegrambot:
    container_name: telegram-bot
    build: ./src
    restart: always
volumes:
  pg_data:
