version: "3.3"

services:
  database:
    container_name: postgres-db
    build: ./db
    env_file:
      - ./db/.env
    volumes:
      - ./db/pg_data:/pg-data
    ports:
      - "5432:5432"
    restart: always
    user: 999:1001
  telegrambot:
    container_name: telegrambot-src
    build: ./src
    restart: always
    environment:
      - TERM=xterm
volumes:
  pg_data:
